name: Explainme
markdown: kramdown
highlighter: pygments
exclude: ["LICENSE.txt", "README.md"]

baseurl: ""
permalink: /:title/


# Paginate
#paginate: 1
#paginate_path: "/pagination/page:num/"


# Plugins
plugins:
  - jekyll-multiple-languages-plugin
  - jekyll-paginate


# jekyll-multiple-languages-plugin settings:
languages: ["en","ge","fr","du","es","it","pt","ru","ja","ch","ko","hi","te","ma","ta","tr","gr","pl","cz","hu","sw","da","fi","uk","ar","in"]


exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico"]


email: explainme@mailbox.org
description: >-
  Welcome to Explainme,that brings easy-to-understand educational videos to people everywhere.
  Our goal is to spread knowleage, no matter their age or where they live.
  We cover many topics. Our team loves to create videos that make difficult subjects simple and enjoyable to understand.
  Join us on our learning journey and discover something new every week!
twitter_username: jekyllrb
github_username:  jekyll